spring:
  application:
    name: ibo-service

  datasource:
    url: "<your_db_url"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: <your_db_username>
    password: <your_db_password>
  flyway:
    default-schema: "ibo_db"
    locations: "classpath:db/migration"
    schemas: "ibo_db"
    validate-on-migrate: on


