spring:
  application:
    name: ibo-service

  datasource:
    url: "jdbc:mysql://ibo-db.cij9ycjxeyv6.us-east-1.rds.amazonaws.com:3306/ibo_db"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: K6d4aT9Zm2qo617sffma
  flyway:
    default-schema: "ibo_db"
    locations: "classpath:db/migration"
    schemas: "ibo_db"
    validate-on-migrate: on


